### ISSUE TITLE
Multiple label support

### ISSUE THREAD

**Issue by MaxOstrowski** [potassco/clingraph#16]
```
attr(node, a, label, "myA").
attr(node, a, label, "additional a description").
```

I would like to have multiple labels on nodes and edges. Maybe they can be drawn next to each other, maybe stacked on top, sorted lexicographically ? With this feature it would be possible to combine several symbols in a nice looking way without having to write string magic on top.

**Comment by susuhahnml** [comment]
Before I read this I already posted another issue #19 with some ideas to do this.
