### ISSUE TITLE
add_fact_string raises InvalidSyntax

### ISSUE THREAD

**Issue by florianfischer91** [potassco/clingraph#47]
When piping a fact-string into clingraph, the method `add_fact_string` raises an `InvalidSyntax` error due to a RuntimeError `too many messages` (i think this comes from clingo). 
My string contains facts where an argument contains double quotes, so i think this somehow causes the error?
But when i pipe the fact-string directly into clingo i don't get any error, so the string should be OK, right? And when i remove `program = program.replace('\\','\\\\')` from `add_fact_string` i also don't get any error.

So do you have any idea how i can get rid of this error or how the input-str needs to be escaped properly?

P.S.: Thanks for developing this library it's quite useful :-)

**Comment by florianfischer91** [comment]
Here is a small example to verify the error [graph.txt](https://github.com/potassco/clingraph/files/8101906/graph.txt)
Just run it with 
```python
from clingraph import Clingraph

c = Clingraph(type_="digraph")

with open("graph.txt") as f:
    facts = f.read()

c.add_fact_string(facts) # throws InvalidSyntax error
# c.add_fact_file("graph.txt") # this works

c.compute_graphs()

c.save_gif()

``` 
Additionally i noticed that when a string contains double quotes at the end of a string f.i.
```prolog
attr(node, jane, label, "\"quoted \n with newline\"").
```
an invalid dot-string will be created
```dot
//----------default----------
digraph default {
        graph [label="\"Quoted\"s"]
        node [style=filled]
        john [label="\"Quoted text\"s"]
//missing " at the end
        jane [label="\"quoted \n with newline\"] 
        john -> jane
}
```

**Comment by susuhahnml** [comment]
Hi! I will take a look at all this. The issue here is to get the escape characters from the input all the way to the dot output. As soon as I have a solution I will post it here.

**Comment by susuhahnml** [comment]
This will be fixed in the next version. There you can run:

```
from clingraph import Factbase, compute_graphs
from clingraph.graphviz.imageio import save_gif

fb = Factbase()

with open("graphs.txt") as f:
    facts = f.read()

fb.add_fact_string(facts)
# c.add_fact_file("graph.txt") # this works

graphs = compute_graphs(fb,graphviz_type="digraph")

save_gif(graphs)
```

**Comment by susuhahnml** [comment]
This is now fixed in the new version https://github.com/potassco/clingraph/discussions/56 @florianfischer91
