### ISSUE TITLE
Multiple runs with same input leads to a different layout of graphs

### ISSUE THREAD

**Issue by florianfischer91** [potassco/clingraph#48]
When running clingraph with the same input (sorted list of facts) i get a different layout of the graphs (different position of nodes) and also a different order of subgraphs. 
AFAIK graphviz itself should be deterministic (at least when using same version).

If it is possible it would be cool that clingraph would always produce the same output for a specific input.

**Comment by susuhahnml** [comment]
Hi! @florianfischer91 This will be in the next version. Should be out soon, I can keep you posted.

**Comment by susuhahnml** [comment]
This should be now in the new version https://github.com/potassco/clingraph/discussions/56
