### ISSUE TITLE
json not accepted as input file

### ISSUE THREAD

**Issue by MaxOstrowski** [potassco/clingraph#57]
```
clingraph --json sol.json
ERROR:  - The json can not be read.
Expecting value: line 1 column 1 (char 0)
```
while
`cat sol.json | clingraph --json`
works

**Comment by susuhahnml** [comment]
Hi I added in the documentation that json is now only working from stdin not as file. Files are supposed to only be for facts, that way I avoid having multiple jsons as inputs which I felt had a strange meaning. I can see if is needed as a new feature, because you could always pipe it...

**Comment by MaxOstrowski** [comment]
Could I recommend to hide all this burden from the user (and remove the `--json` option) and simply detect if either the stream of a file contains facts or a json ? No matter if piped or as argument. And maybe simply throw an error if more than one json input is detected.

**Comment by susuhahnml** [comment]
I added this already in this new version. You can try it out @MaxOstrowski

**Comment by MaxOstrowski** [comment]
In your commit messages you can write #57 to link it to this issue, then every commit you do is already shown here in the issue, making it easier to see what changed.
Thanks for adding the auto-detection function, makes my live much easier and less options for the user. :heart: 

Unfortunately, I now get:
```
WARNING:  - Only satisfiable results in the JSON can be parsed
clingraph.exceptions.InvalidSyntaxJSON: The JSON indicates a result that is not SATISFIABLE
```
In my json the result field is set to:
```  
"Result": "OPTIMUM FOUND",
```

produced with
`--quiet=1 --outf=2`

Would be cool if this check could be extended to optimal (and maybe even non-optimal in case of timeout) solutions. Or is there any reason why it checks for `SATISFIABLE` ? If the result is `UNSATISFIABLE` there won't be any model. Otherwise either one or more models occur.

I also do not know what the appropriate behaviour would be for `brave` and `cautious` consequences.

**Comment by susuhahnml** [comment]
I didnt think of these cases. I could leave the error as a warning when is unsat and allow all the other results... or what behavior were you thinking of @MaxOstrowski ?

**Comment by MaxOstrowski** [comment]
Works like a charm. Thanks
