### ISSUE TITLE
No output files produced

### ISSUE THREAD

**Issue by MaxOstrowski** [potassco/clingraph#58]
Installed clingraph via:
'conda install -c potassco/label/dev clingraph`

Any call, like:
`clingraph exaples/lights/lights.lp --out=render --dir='out/lights' --view --select-graph=house_1 --format=png`
Only produces dot output on the terminal like
```
//----------house_1----------
graph house_1 {
	graph [name="Big House" nodesep=1 type="graph"]
	edge [style=dotted]
	lhub_1 [label=HUB]
	lhub_1 -- lbathroom_1
	lhub_1 -- lbedroom_1
	lhub_1 -- llivingroom2_1
	lhub_1 -- llivingroom1_1
	subgraph cluster_bedroom_1 {
		graph [label=Bedroom style=dashed]
		lbedroom_1 [label="Bed light" color=lightblue shape=circle style=filled]
	}
	subgraph cluster_livingroom_1 {
		graph [label=Livingroom style=dashed]
		llivingroom1_1 [label="Main light" color=lightblue shape=circle style=filled]
		llivingroom2_1 [label="Kitchen light" color=lightblue shape=circle style=filled]
		subgraph cluster_bathroom_1 {
			graph [label=Bathroom style=dotted]
			lbathroom_1 [label=Light color=lightblue shape=circle style=filled]
		}
	}
}
```
but no files in `out` or `out/lights` or anywhere else. Also `--view` does not pop up any produced file.

**Comment by susuhahnml** [comment]
This is the old version output. Apparently there was an error updating the conda package which I will check today.

**Comment by susuhahnml** [comment]
@MaxOstrowski The new version should have this fixed

**Comment by MaxOstrowski** [comment]
Thanks, I do get a picture now.
