### ISSUE TITLE
Remove print-statement in _render_single_graph

### ISSUE THREAD

**Issue by florianfischer91** [potassco/clingraph#63]
Currently a print-statement is executed when rendering a graph
![image](https://user-images.githubusercontent.com/72799603/158168262-81029f7d-3103-4362-8f6b-d5f9cb388aa0.png)

Is it possible to remove it and perhaps return the file_path instead?

**Comment by florianfischer91** [comment]
To inform the user where the image was saved makes totally sense if you use it as a console-application.
But in my use case I would like to use clingraph as a library and create graphs along a toolchain. So to either inform the user of my application under which name the file was saved or do something else with the file afterwards, i would need to build the path manually.
Returning the path was just an idea. If it doesn't fit in the overall concept it's ok for me :-)

**Comment by susuhahnml** [comment]
Ok, I understand what you mean now. I think it makes sense to return the path and only print when using the console functionality, let me see if I can include that in the next version.

**Comment by susuhahnml** [comment]
Done! I hope this helps :) Thank you for the feedback.
