### ISSUE TITLE
select-model option

### ISSUE THREAD

**Issue by tortinator** [potassco/clingraph#69]
The command `clingo --outf=2 multipleC.lp -c n=10 0 | clingraph --out=dot --select-model 1  --select-model 8` with
[multipleC.txt](https://github.com/potassco/clingraph/files/8347393/multipleC.txt)

gives me only one graphs rather than two - what am I doing wrong?

**Comment by susuhahnml** [comment]
Nothing! It should give you two. Is a bug with the parameter parsing that I fixed already but haven't published. I can deploy today 😃
