### ISSUE TITLE
Decide if the graph should be printed `on_model` or `print_model`

### ISSUE THREAD

**Issue by susuhahnml** [potassco/clingraph#7]
`on_model`:
 - User can silence the stable model but still get the graph

`print_model`:
 - Needed if you only want graphs for optimal models

**Comment by MaxOstrowski** [comment]
clingraph shouldn't need to call `clingo` and the callback methods to produce a graph.
If used as a library #15 is should probably return a graphviz object, graphviz text data or a file location with the rendered image.
As input it should probably accept either a clorm factbase, a collection of strings, or a collection of files (or any mixture of those).

In this way we could also use it for systems like `clingo-dl` or `clingcon` or any other systems developed in the future. It would also be possible to render models already stored in a database or file.

**Comment by susuhahnml** [comment]
I agree with all this @MaxOstrowski ! We will restructure the project to allow all of this functionalities. When the input is a collection of files you mean the current behaviour were we call clingo with all the files? And if so, then we would still need to think of how to answer the question for this issue

**Comment by MaxOstrowski** [comment]
I (personally) would only allow a collection of files that represent facts. This is exactly hat `clorm` excepts as input.
So no choice rules or integrity constraints, but simple, deterministic rules and include statements.
