### ISSUE TITLE
options render and gif

### ISSUE THREAD

**Issue by tortinator** [potassco/clingraph#70]
I wonder whether option `gif` should not rather be sth like `animate`

`gif` an ouput format, like `pdf` or `png`, rather than a functional term

**Comment by tortinator** [comment]
@susuhahnml What si your take on it? This is relevant to the paper!

**Comment by susuhahnml** [comment]
Hi! Sorry for the late response. We could do `--out=animate` instead of `--out=gif`, but I would change the format, `--out=animate` should not require any format specification. What do you think?

**Comment by tortinator** [comment]
That would be nice, and I agree with your suggestion though who knows whether in the long run we'll have alternative animation formats but not now of course

I'll open an issue in the paper repo to change things once done in clingraph
