### ISSUE TITLE
clingraph is super slow on some graphs

### ISSUE THREAD

**Issue by rkaminsk** [potassco/clingraph#83]
Here is an [example (example.zip)](https://github.com/potassco/clingraph/files/9692757/example.zip) for an animated graph that has about 200 nodes and 50 time steps. Producing the facts takes about 5 seconds (due to a somewhat inefficient encoding) but producing the dot file takes half an hour.

```bash
➜ cat viz.json | time clingraph --prefix=viz_ --viz-encoding ./viz.lp --out=facts > /dev/null 
4.96s user 0.09s system 99% cpu 5.047 total
➜ cat viz.json | time clingraph --prefix=viz_ --viz-encoding ./viz.lp --out=dot > /dev/null
1950.94s user 0.26s system 99% cpu 32:31.36 total
```

Maybe this is also linked to #79. Please help. It would be some much more fun to have a faster clingraph.

**Comment by sthiele** [comment]
The patched version is definetly faster on my system.
```
clingraph --prefix=viz_ --viz-encoding ./viz.lp --out=dot >  177,40s user 0,26s system 99% cpu 2:57,83 total
```

**Comment by rkaminsk** [comment]
> The patched version is definetly faster on my system.
> 
> ```
> clingraph --prefix=viz_ --viz-encoding ./viz.lp --out=dot >  177,40s user 0,26s system 99% cpu 2:57,83 total
> ```

Still not exactly fast but at least in the realm of usable. Given the amount of data involved it should be possible to compute this within seconds. Something inefficient is happening somewhere...

**Comment by rkaminsk** [comment]
One can speed this up drastically using the FactBase with an index:
```bash
➜ cat viz.json | time clingraph --prefix=viz_ --viz-encoding ./viz.lp --out=dot > /dev/null
18.50s user 0.08s system 94% cpu 19.623 total
```

For this, the `FactBase` in `orm.py` has to be created with
```python
self.fb = ClormFactBase(indexes=[Attr.element_id])
```
See also <https://clorm.readthedocs.io/en/docs/clorm/factbase.html#factbases-with-indexes>.
