### ISSUE TITLE
Problems with installation under windows using conda 

### ISSUE THREAD

**Issue by matthiasknorr** [potassco/clingraph#93]
Though not a regular Windows user needed to install clingraph under windows.

I tried the first option:
$ conda install -c potassco clingraph

It does not find the packages (on the current channels - I can send the complete error message if that helps).

I then tried the second one:
$ conda install -c potassco/label/dev clingraph

It seemingly installs, but then calling any example command yields a process that tries to open some file.

Following the pip instructions, it worked just fine.

**Comment by susuhahnml** [comment]
Hi! Thanks for the input @matthiasknorr. At the moment, for the lastest version, we are only supporting pip.
